[project]
name = "server-capstone-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.7",
    "gunicorn>=23.0.0",
    "pillow>=12.0.0",
    "psycopg[binary]>=3.2.10",
    "python-telegram-bot>=22.5",
    "requests>=2.32.5",
    "uvicorn>=0.37.0",
]
