# Generated by Django 5.2.6 on 2025-09-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=['/home/gabrields/MEGA/Projects/final-project-frontend/monitor/static'])),
            ],
        ),
    ]
