# Generated by Django 5.2.6 on 2025-09-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myimage',
            name='title',
        ),
        migrations.AlterField(
            model_name='myimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
