# Generated by Django 5.2.6 on 2025-09-26 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_remove_myimage_title_alter_myimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myimage',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='myimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
