# Generated by Django 5.2.7 on 2025-10-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_myimage_options_myimage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='myimage',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myimage',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed_images/'),
        ),
    ]
