# Generated by Django - minimal migration for TelegramUser
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, auto_created=True, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=150, blank=True, null=True)),
                ('username', models.CharField(max_length=150, blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
